- hosts: docker
  gather_facts: true
  become: yes
  tasks:
    - name: Check if Docker Engine is installed
      stat:
        path: /usr/bin/docker
      register: docker_engine_installed
      ignore_errors: yes

    - name: Check if Docker CLI is installed
      stat:
        path: /usr/bin/docker-compose
      register: docker_cli_installed
      ignore_errors: yes

    - name: Install Docker Engine
      apt:
        name: docker.io
        state: present
      when: docker_engine_installed.stat.exists == false

    - name: Install Docker CLI
      apt:
        name: docker-compose
        state: present
      when: docker_cli_installed.stat.exists == false

    - name: Start Docker service if not running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull jupyter Docker image
      docker_image:
        name: jupyter/minimal-notebook
        source: pull

    - name: Run jupyter Docker container
      docker_container:
        name: jupyter-uat-1
        image: jupyter/minimal-notebook
        state: started

